### ISSUE TITLE
Error due to a new field "cpuFrequency"

### ISSUE THREAD

**Issue by Iqqdd99** [eu-nebulous/optimiser-controller#49]
The component is not able to handle the field cpuFrequency from a NodeCandidate when trying to deploy an app.

```
{"@timestamp":"2024-12-03T11:31:57.951745555Z","@version":"1","message":"Default on delivery for delivery for topic://eu.nebulouscloud.cfsb.get_node_candidates_multi.reply","logger_name":"eu.nebulouscloud.exn.core.Consumer","thread_name":"pool-1-thread-9","level":"DEBUG","level_value":10000}
{"@timestamp":"2024-12-03T11:31:57.965235138Z","@version":"1","message":"Processing message fortopic://eu.nebulouscloud.cfsb.get_node_candidates_multi.reply","logger_name":"eu.nebulouscloud.exn.core.Consumer","thread_name":"pool-1-thread-9","level":"DEBUG","level_value":10000}
Exception in thread "Thread-0" java.lang.IllegalArgumentException: Unrecognized field "cpuFrequency" (class org.ow2.proactive.sal.model.Hardware), not marked as ignorable (10 known properties: "state", "owner", "cores", "location", "id", "providerId", "disk", "ram", "fpga", "name"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.ow2.proactive.sal.model.NodeCandidate["hardware"]->org.ow2.proactive.sal.model.Hardware["cpuFrequency"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4624)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4555)
	at eu.nebulouscloud.optimiser.controller.ExnConnector.lambda$findNodeCandidatesMultiple$3(ExnConnector.java:640)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at eu.nebulouscloud.optimiser.controller.ExnConnector.findNodeCandidatesMultiple(ExnConnector.java:643)
	at eu.nebulouscloud.optimiser.controller.NebulousAppDeployer.deployApplication(NebulousAppDeployer.java:435)
	at eu.nebulouscloud.optimiser.controller.NebulousApp.deploy(NebulousApp.java:737)
	at eu.nebulouscloud.optimiser.controller.ExnConnector$PerformanceIndicatorMessageHandler.lambda$onMessage$0(ExnConnector.java:359)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "cpuFrequency" (class org.ow2.proactive.sal.model.Hardware), not marked as ignorable (10 known properties: "state", "owner", "cores", "location", "id", "providerId", "disk", "ram", "fpga", "name"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.ow2.proactive.sal.model.NodeCandidate["hardware"]->org.ow2.proactive.sal.model.Hardware["cpuFrequency"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1153)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2241)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1793)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1743)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:576)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:446)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4619)
	... 14 more
{"@timestamp":"2024-12-03T11:32:00.194359079Z","@version":"1","message":"Processing scheduled executor [health] topic://eu.nebulouscloud.optimiser_controller.health  ","logger_name":"eu.nebulouscloud.exn.core.Manager","thread_name":"pool-1-thread-8","level":"DEBUG","level_value":10000}
```

Tested with prod and dev env.

**Comment by rudi** [comment]
We use the sal-common library to parse this json.  I'll check if the sal-common library supports this field.

**Comment by rudi** [comment]
https://github.com/ow2-proactive/scheduling-abstraction-layer/blob/424e7ebfc4853409652ced0b0e5ef19d9045eb1e/sal-common/src/main/java/org/ow2/proactive/sal/model/Hardware.java#L44 says this attribute is supported, so the container should be regenerated with updated dependencies as soon as the sal-common snapshot is updated.  No code changes in optimiser-controller should be necessary.

**Comment by robert-sanfeliu** [comment]
Thanks Rudi, I will tell Ankica

**Comment by rudi** [comment]
will fix soon, no action needed from Ankica

**Comment by rudi** [comment]
The only thing I need to be informed is if the version number of sal-common (or exn-connector-java) change, so I can update the dependency information.
